### ISSUE TITLE
[1강] p.75 Adjacency Matrix 속 수식 L의 의미

### ISSUE THREAD

**Issue by sun1187** [ML-with-Graphs-Study/CS224W#2]
1강 p.75에서 
인접행렬에서 node degree 고려시 해당 행/열의 1 숫자를 센다고 하였습니다.

여기서 k_i가 node i번째의 차수인데, L이 어떤걸 의미하는 지 모르겠습니다.

<img width="601" alt="스크린샷 2022-02-19 오후 3 40 25" src="https://user-images.githubusercontent.com/70509258/154789851-2ce1d48d-8b3c-445f-9b39-d5f377783e4e.png">

**Comment by dongwoo338** [comment]
L이 다른 비슷한 부분 설명하는 곳에선 안나오긴 하지만,
의미상 간선의 수로 보는게 맞는 것 같아요
(그건 그렇고 강의랑 PPT자료가 미묘하게 다르네요 ㅎㅎ)

**Comment by sun1187** [comment]
아하 그렇군요! 답변 감사합니다~
