### ISSUE TITLE
[2강] Graph Isomorphism 판단

### ISSUE THREAD

**Issue by sun1187** [ML-with-Graphs-Study/CS224W#4]
2강 p.26 하단에 Graph Isomorphism 에 관한 이야기가 있습니다.

두 그래프가 같은 방식으로 같은 수의 노드를 포함하면 Isomorphic하다는 말인데
밑에 Isomorphic과 Non-Isomorphic 예시가 이해가 가지 않는데, 어떻게 구분하죠?

<img width="732" alt="스크린샷 2022-02-19 오후 5 44 31" src="https://user-images.githubusercontent.com/70509258/154793759-7699df54-a3fb-41ac-a157-49fdd6ba471a.png">

**Comment by arkdusdyk** [comment]
Isomorphism이 Node 와 그 연결 관계가 동일한 형태일때를 의미하는데,

왼쪽 그림은 node mapping 관계를 봤을때 점들의 위치만 이동한다고 상상하면 결국 같은 형태이다 (동형) 라는걸 확인할 수 있어요.

오른쪽 그림에서 설명에 써있는 cycle length가 3 이고 아니고의 의미는 잘 파악이 안되지만, 그림을 통해서 봤을때 두 그림의 연결 상태가 다르기 때문에 동형이 될 수 없다는 의미입니다!

**Comment by sun1187** [comment]
아하 말씀 듣고 그림 그려서 하니 이해가 잘 갔습니다.
답변 감사합니다~

<img width="476" alt="스크린샷 2022-02-20 오전 9 16 00" src="https://user-images.githubusercontent.com/70509258/154823516-607b4266-6cf6-4671-9fc6-3d6e0872d2f7.png">
